package gr.ntua.ece.softeng;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import gr.ntua.ece.softeng.Parent;
import gr.ntua.ece.softeng.ParentRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class ParentController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private ParentRepository parentRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewParent (@RequestParam String FirstName
			, @RequestParam String LastName, @RequestParam String username, @RequestParam String password,
			@RequestParam String email , @RequestParam String PhoneNumber, @RequestParam String DebitCard) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Parent p = new Parent();
		p.setFirstName(FirstName);
		p.setLastName(LastName);
		p.setUsername(username);
		p.setPassword(password);
		p.setEmail(email);
		p.setPhoneNumber(PhoneNumber);
		p.setDebitCard(DebitCard);
		p.setFpoints(null);
		parentRepository.save(p);
		return "Saved";
	}	


	@GetMapping(path="/all")
	public @ResponseBody Iterable<Parent> getAllParents() {
		// This returns a JSON or XML with the users
		return parentRepository.findAll();
	}

}
